Models/ErrorViewModel.cs
namespace entityFrameworkCoreApp.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/HomeController.cs
using entityFrameworkCoreApp.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace entityFrameworkCoreApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/OgrenciController.cs
using entityFrameworkCoreApp.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Data;
using System.Linq.Expressions;

namespace entityFrameworkCoreApp.Controllers
{
    public class OgrenciController : Controller
    {
        private readonly DataContext _context;
        public OgrenciController(DataContext context)
        {

            _context = context;

        }
        public async Task<IActionResult> Index()  //öğrenciler i listeliyoruz burada .
        {
            return View(await _context.Ogrenciler.ToListAsync());
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(Ogrenci model)
        {
            _context.Ogrenciler.Add(model);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }
        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var ogr = await _context.Ogrenciler.FindAsync(id);

            if (ogr == null)
            {
                return NotFound();
            }
            return View(ogr);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id , Ogrenci model)
        {
            if (id != model.Id)
            {
                return NotFound();
            }
            if(ModelState.IsValid) 
            {
                try
                {
                    _context.Update(model);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {

                    if (!_context.Ogrenciler.Any(o => o.Id == model.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
               
            }
            return View(model);

        }
        [HttpGet]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var ogrenci = await _context.Ogrenciler.FindAsync(id);

            if (ogrenci == null)
            {
                return NotFound();
            }
            return View(ogrenci);
        }
        [HttpPost]
        public async Task<IActionResult> Delete([FromForm]int id)
        {
            var ogrenci = await _context.Ogrenciler.FindAsync(id);
            if (ogrenci == null)
            {
                return NotFound();
            }            
            _context.Ogrenciler.Remove(ogrenci);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Ogrenci/Create.cshtml
@model Ogrenci

<h2>Öğrenci Ekle</h2>
<hr>
<form asp-controller="Ogrenci" asp-action="Create" method="post">
    <div class="mb3">
        <label asp-for="OgrenciAd" class="form-label">Öğrenci Adı</label>
        <input asp-for="OgrenciAd" class="form-control">
    </div>
    <div class="mb3">
        <label asp-for="OgrenciSoyad" class="form-label">Öğrenci Soyad</label>
        <input asp-for="OgrenciSoyad" class="form-control">
    </div>
    <div class="mb3">
        <label asp-for="Eposta" class="form-label">Eposta</label>
        <input asp-for="Eposta" class="form-control">
    </div>
    <div class="mb3">
        <label asp-for="Telefon" class="form-label">Telefon</label>
        <input asp-for="Telefon" class="form-control">
    </div>
    
    <button type="submit" class="btn btn-secondary">Kaydet</button>
   

</form>

Views/Ogrenci/Delete.cshtml
@model Ogrenci
<p>
    <b>@Model.OgrenciAd @Model.OgrenciSoyad</b> isimli öğrenciyi silmek istiyor musunuz?

    <form asp-action="Delete" method="post">
        <input type="hidden" value="@Model.Id"name="id">
        <button type="submit" class="btn btn-danger">Evet</button>
        <a asp-action="Index" class="btn btn-primary">Hayır</a> 
    </form>      
</p>

Views/Ogrenci/Edit.cshtml
@model Ogrenci

<h2>Öğrenci Ekle</h2>
<hr>
<form asp-controller="Ogrenci" asp-action="Edit" method="post">
    <input type="hidden" asp-for="Id"/> 
    <div class="mb3">
        <label asp-for="OgrenciAd" class="form-label">Öğrenci Adı</label>
        <input asp-for="OgrenciAd" class="form-control">
    </div>
    <div class="mb3">
        <label asp-for="OgrenciSoyad" class="form-label">Öğrenci Soyad</label>
        <input asp-for="OgrenciSoyad" class="form-control">
    </div>
    <div class="mb3">
        <label asp-for="Eposta" class="form-label">Eposta</label>
        <input asp-for="Eposta" class="form-control">
    </div>
    <div class="mb3">
        <label asp-for="Telefon" class="form-label">Telefon</label>
        <input asp-for="Telefon" class="form-control">
    </div>
    
    <button type="submit" class="btn btn-secondary">Kaydet</button>
   

</form>

Views/Ogrenci/Index.cshtml
@model IEnumerable<Ogrenci>

<h2>Öğrenci Güncelleme</h2>
<a href="/Ogrenci/Create" class="btn btn-primary">Öğrenci Ekle</a>
<table class="table"
    <thead>
        <tr>
            <td>Öğrenci Id</td>
            <td>Öğrenci Ad</td>
            <td>Öğrenci Soyad</td>
            <td></td>
        </tr>
    </thead>
    <tbody>
        @foreach (var ogrenci in Model)
        {
            <tr>
                <td>@ogrenci.Id</td>
                <td>@ogrenci.OgrenciAd</td>
                <td>@ogrenci.OgrenciSoyad</td>
                <td>
                <a asp-action="Edit" asp-route-id="@ogrenci.Id" class="btn btn-sm btn-primary">Edit</a>
                <a asp-action="Delete" asp-route-id="@ogrenci.Id" class="btn btn-sm btn-danger">Delete</a>
                </td>
            </tr>
        }

    </tbody>    
</table>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - entityFrameworkCoreApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/entityFrameworkCoreApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">entityFrameworkCoreApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Ogrenci" asp-action="Index">Öğrenciler</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - entityFrameworkCoreApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>